// SPDX-FileCopyrightText: 2024 vivi developers <vivi-ui@tuta.io>
// SPDX-License-Identifier: MIT

export { AppBar } from "./magic/app_bar.slint";
export { Border, BorderStyle } from "./foundation.slint";
export { CheckBox } from "./magic/check_box.slint";
export { CircularProgressSlider } from "./magic/circular_progress_slider.slint";
export { ComboBox, ComboBoxItem, PopupPosition } from "./magic/combobox.slint";
export { FormElement } from "./magic/form_element.slint";
export { GroupBox } from "./magic/group_box.slint";
export { IconButton } from "./magic/icon_button.slint";
export { Icons } from "./magic/icons.slint";
export { StateLayer } from "./magic/state_layer.slint";
export { TabBar, TabBarItem } from "./magic/tab_bar.slint";
export { TextButton } from "./magic/text_button.slint";
export { TextField } from "./magic/text_field.slint";
export { TextArea } from "./magic/text_area.slint";
export { Time, TimePickerStyle, TimePickerPopup } from "./magic/time_picker_popup.slint";
export { FilledButton } from "./magic/filled_button.slint";
export { MagicHorizontalBox } from "./magic/magic_horizontal_box.slint";
export { OutlineButton } from "./magic/outline_button.slint";
export { ButtonAction, MagicButtonBase } from "./magic/magic_button_base.slint";
export { MagicText } from "./magic/magic_text.slint";
export { MagicIcon } from "./magic/magic_icon.slint";
export { MagicProgressSliderBase } from "./magic/magic_progress_slider_base.slint";
export { MagicListViewStyle, MagicListViewItemStyle, MagicListViewItem, MagicListView } from "./magic/magic_list_view.slint";
export { MagicWindow } from "./magic/magic_window.slint";
export { ProgressSlider } from "./magic/progress_slider.slint";
export { ScrollView } from "./magic/scroll_view.slint";
export { Switch } from "./magic/switch.slint";
export { ListView } from "./magic/list_view.slint";
export { MagicVerticalBox } from "./magic/magic_vertical_box.slint";
export { LayoutStyle } from "./foundation.slint";
export {
    Palette,
    AnimationSettings,
    FontSettings,
    LayoutSettings,
    SizeSettings,
    BorderSettings,
    MagicPalette,
    Flavor,
    CatppuccinPalette,
    Catppuccin,
    IconSettings
} from "./magic/styling.slint";
