# SPDX-FileCopyrightText: 2024 vivi developers <vivi-ui@tuta.io>
# SPDX-License-Identifier: MIT

[book]
authors = ["Vivi"]
language = "en"
multilingual = false
src = "src"
title = "vivi 0.2 reference"
