// SPDX-FileCopyrightText: 2024 vivi developers <vivi-ui@tuta.io>
// SPDX-License-Identifier: MIT

import { BorderStyle, Border } from "./border.slint";
import { IconStyle } from "./icon_base.slint";
import { TextStyle } from "./text_base.slint";
import { LayoutStyle } from "./vertical_layout_base.slint";

export enum PopupPosition {
    top,
    bottom
}

export struct ComboBoxItemStyle {
    // background_layer
    border_style: BorderStyle,

    // content_layer
    text_style: TextStyle,

    // layout
    layout_style: LayoutStyle
}

export struct ComboBoxStyle {
    // background_layer
    border_style: BorderStyle,

    // content_layer
    icon_style: IconStyle,
    text_style: TextStyle,
    placeholder_style: TextStyle,

    // layout
    layout_style: LayoutStyle,

    // items
    item_style: ComboBoxItemStyle,

    // popup
    popup_border_style: BorderStyle,
}

export struct ComboBoxItem {
    text: string
}

export component ComboBoxBase {
    in property <bool> enabled: true;
    in property <[ComboBoxItem]> model;
    in_out property <int> current_index: -1;
    out property <ComboBoxItem> current_value: root.model[root.current_index];
    in property <string> placeholder_text;
    in property <PopupPosition> popup_position: PopupPosition.bottom;
    in property <ComboBoxStyle> style;

    callback selected(/* index */ int);

    accessible_role: combobox;

    background_layer := Border {
        style: root.style.border_style;
    }

    @children

}
