// SPDX-FileCopyrightText: 2024 vivi developers <vivi-ui@tuta.io>
// SPDX-License-Identifier: MIT

import { BorderStyle, Border } from "./border.slint";
import { IconStyle } from "./icon_base.slint";
import { TextStyle } from "./text_base.slint";
import { LayoutStyle } from "./vertical_layout_base.slint";

export struct TextInputStyle {
    // background_layer
    border_style: BorderStyle,

    // selection
    selection_background: brush,
    selection_foreground: brush,

    // content_layer
    icon_style: IconStyle,
    text_style: TextStyle,
    placeholder_style: TextStyle,

    // layout
    layout_style: LayoutStyle
}

export component TextInputBaste {
    in property <bool> enabled: true;
    in property <bool> has_error;
    in_out property <string> text;
    in property <string> placeholder_text;
    in property <TextInputStyle> style;

    callback accepted(/* text*/ string);
    callback edited(/* text*/ string);

    background_layer := Border {
        style: root.style.border_style;
    }

    @children
}
