// SPDX-FileCopyrightText: 2024 vivi developers <vivi-ui@tuta.io>
// SPDX-License-Identifier: MIT

import { ButtonStyle } from "../foundation.slint";
import { ButtonAction } from "./magic_button_base.slint";
import { MagicText } from "./magic_text.slint";
import { MagicIcon } from "./magic_icon.slint";
import { OutlineButton } from "./outline_button.slint";
import {
    Palette,
    FontSettings,
    IconSettings,
    SizeSettings,
    LayoutSettings,
    BorderSettings
} from "./styling.slint";

export component FilledButton inherits OutlineButton {
    in property <ButtonAction> action;

    property <ButtonStyle> default_style: {
        border_style: {
            background: Palette.control_background,
            border_radius: BorderSettings.control_border_radius,
        },
        text_style: {
            font_size: FontSettings.body.font_size,
            font_weight: FontSettings.body.font_weight,
            foreground: Palette.control_foreground,
        },
        icon_style: {
            icon_size: IconSettings.body.icon_size,
            foreground: Palette.control_foreground,
        },
        layout_style: LayoutSettings.control_style
    };

    property <ButtonStyle> primary_style: {
        border_style: {
            background: Palette.accent_background,
            border_radius: BorderSettings.control_border_radius,
        },
        text_style: {
            font_size: FontSettings.body.font_size,
            font_weight: FontSettings.body.font_weight,
            foreground: Palette.accent_foreground,
        },
        icon_style: {
            icon_size: IconSettings.body.icon_size,
            foreground: Palette.accent_foreground,
        },
        layout_style: LayoutSettings.control_style
    };

    property <ButtonStyle> destructive_style: {
        border_style: {
            background: Palette.destructive_background,
            border_radius: BorderSettings.control_border_radius,
        },
        text_style: {
            font_size: FontSettings.body.font_size,
            font_weight: FontSettings.body.font_weight,
            foreground: Palette.destructive_foreground,
        },
        icon_style: {
            icon_size: IconSettings.body.icon_size,
            foreground: Palette.destructive_foreground,
        },
        layout_style: LayoutSettings.control_style
     };

    style: root.action == ButtonAction.default ? root.default_style :
        root.action == ButtonAction.primary ? root.primary_style : root.destructive_style;
}
