// SPDX-FileCopyrightText: 2024 vivi developers <vivi-ui@tuta.io>
// SPDX-License-Identifier: MIT

export global Icons {
    out property <image> add: @image_url("../assets/icons/add.svg");
    out property <image> arrow_back: @image_url("../assets/icons/arrow_back.svg");
    out property <image> arrow_downward: @image_url("../assets/icons/arrow_downward.svg");
    out property <image> arrow_drop_down: @image_url("../assets/icons/arrow_drop_down.svg");
    out property <image> arrow_forward: @image_url("../assets/icons/arrow_forward.svg");
    out property <image> arrow_upward: @image_url("../assets/icons/arrow_upward.svg");
    out property <image> arrow_right: @image_url("../assets/icons/arrow_right.svg");
    out property <image> book: @image_url("../assets/icons/book.svg");
    out property <image> brush: @image_url("../assets/icons/brush.svg");
    out property <image> calculate: @image_url("../assets/icons/calculate.svg");
    out property <image> check: @image_url("../assets/icons/check.svg");
    out property <image> clear: @image_url("../assets/icons/clear.svg");
    out property <image> computer: @image_url("../assets/icons/computer.svg");
    out property <image> description: @image_url("../assets/icons/description.svg");
    out property <image> folder: @image_url("../assets/icons/folder.svg");
    out property <image> format_size: @image_url("../assets/icons/format_size.svg");
    out property <image> home: @image_url("../assets/icons/home.svg");
    out property <image> image: @image_url("../assets/icons/image.svg");
    out property <image> insert_drive_file: @image_url("../assets/icons/insert_drive_file.svg");
    out property <image> keyboard_return: @image_url("../assets/icons/keyboard_return.svg");
    out property <image> light_mode: @image_url("../assets/icons/light_mode.svg");
    out property <image> list: @image_url("../assets/icons/list.svg");
    out property <image> mode_night: @image_url("../assets/icons/mode_night.svg");
    out property <image> more_vert: @image_url("../assets/icons/more_vert.svg");
    out property <image> pin: @image_url("../assets/icons/pin.svg");
    out property <image> reorder: @image_url("../assets/icons/reorder.svg");
    out property <image> search: @image_url("../assets/icons/search.svg");
    out property <image> videogame_asset: @image_url("../assets/icons/videogame_asset.svg");
    out property <image> visibility_off: @image_url("../assets/icons/visibility_off.svg");
    out property <image> visibility: @image_url("../assets/icons/visibility.svg");
    out property <image> menu: @image_url("../assets/icons/menu.svg");
    out property <image> storage: @image_url("../assets/icons/storage.svg");
    out property <image> info: @image_url("../assets/icons/info.svg");
    out property <image> castle: @image_url("../assets/icons/castle.svg");
    out property <image> star: @image_url("../assets/icons/star.svg");
    out property <image> print: @image_url("../assets/icons/print.svg");
    out property <image> route: @image_url("../assets/icons/route.svg");
    out property <image> edit: @image_url("../assets/icons/edit.svg");
    out property <image> keyboard: @image_url("../assets/icons/keyboard.svg");

    // filled
    out property <image> filled_audio_file: @image_url("../assets/icons/filled_audio_file.svg");
    out property <image> filled_av_timer: @image_url("../assets/icons/filled_av_timer.svg");
    out property <image> filled_calendar_month: @image_url("../assets/icons/filled_calendar_month.svg");
    out property <image> filled_description: @image_url("../assets/icons/filled_description.svg");
    out property <image> filled_folder: @image_url("../assets/icons/filled_folder.svg");
    out property <image> filled_image: @image_url("../assets/icons/filled_image.svg");
    out property <image> filled_insert_drive_file: @image_url("../assets/icons/filled_insert_drive_file.svg");
    out property <image> filled_settings: @image_url("../assets/icons/filled_settings.svg");
    out property <image> filled_video_file: @image_url("../assets/icons/filled_video_file.svg");
    out property <image> filled_videogame_asset: @image_url("../assets/icons/filled_videogame_asset.svg");
}
