// SPDX-FileCopyrightText: 2024 vivi developers <vivi-ui@tuta.io>
// SPDX-License-Identifier: GPL-3.0-only

import { FontSettings, SizeSettings, Palette } from "./styling.slint";

export component MagicWindow inherits Window {
    in_out property <brush> accent <=> Palette.accent_background;

    background: Palette.background;
    default_font_size: SizeSettings.scale_factor * 14px;
    default_font_weight: FontSettings.body.font_weight;
}
